export const DropdownListForKYC = {
  // Diplamo Discipline
  HSCDiscipline: [
    {
      name: 'Science',
      value: 'Science',
      checkbox: false
    },
    {
      name: 'Commerce',
      value: 'Commerce',
      checkbox: false
    },
    {
      name: 'Arts',
      value: 'Arts',
      checkbox: false
    },
    {
      name: 'Others',
      value: 'Others',
      checkbox: false
    }
  ],
  boards: [
    {
      name: 'CBSE',
      checkbox: false
    },
    {
      name: 'ICSE',
      checkbox: false
    },
    {
      name: 'State Board',
      checkbox: false
    },
    {
      name: 'Others',
      checkbox: false
    }
  ],
  // Gender
  gender: [
    {
      name: 'Male',
      checkbox: false
    },
    {
      name: 'Female',
      checkbox: false
    },
    // {
    //   name: 'Other',
    //   checkbox: false
    // }
  ],
  // Education Level
  level: [
    {
      name: 'SSLC',
      label: 'SSLC / 10th',
      checkbox: false,
      percentageFrom: '',
      percentageTo: '',
      yearFrom: '',
      yearTo: '',
      radio: false
    },
    {
      name: 'HSC',
      label: 'HSC / 12th',
      checkbox: false,
      percentageFrom: '',
      percentageTo: '',
      yearFrom: '',
      yearTo: '',
      radio: false
    },
    {
      name: 'Diploma',
      label: 'Diploma',
      checkbox: false,
      percentageFrom: '',
      percentageTo: '',
      yearFrom: '',
      yearTo: '',
      radio: false
    },
    {
      name: 'UG',
      label: 'Undergraduate',
      checkbox: false,
      percentageFrom: '',
      percentageTo: '',
      yearFrom: '',
      yearTo: '',
      radio: false
    },
    {
      name: 'PG',
      label: 'Postgraduate',
      checkbox: false,
      percentageFrom: '',
      percentageTo: '',
      yearFrom: '',
      yearTo: '',
      radio: false
    }
  ],
  // Backlogs
  backlogs: [
    {
      name: 'Nil',
      checkbox: false
    },
    {
      name: '1',
      checkbox: false
    },
    {
      name: '2',
      checkbox: false
    },
    {
      name: '3',
      checkbox: false
    },
    {
      name: '4 & more',
      checkbox: false
    }
  ],
  // Discipline
  discipline: [
    {
      name: 'Other',
      value: 'Other',
      checkbox: false
    },
    {
      name: 'Civil',
      value: 'Civil',
      checkbox: false
    },
    {
      name: 'Automobile',
      value: 'Automobile',
      checkbox: false
    },
    {
      name: 'Electrical',
      value: 'Electrical',
      checkbox: false
    },
    {
      name: 'Mining',
      value: 'Mining',
      checkbox: false
    },
    {
      name: 'Mechanical',
      value: 'Mechanical',
      checkbox: false
    },
    {
      name: 'Metallurgy',
      value: 'Metallurgy',
      checkbox: false
    },
    {
      name: 'Computer Science',
      value: 'Computer Science',
      checkbox: false
    },
    {
      name: 'Communications',
      value: 'Communications',
      checkbox: false
    },
    {
      name: 'Inst. & Control',
      value: 'Inst. & Control',
      checkbox: false
    },
    {
      name: 'Chemical',
      value: 'Chemical',
      checkbox: false
    },
    {
      name: 'Construction Management',
      value: 'Construction Management',
      checkbox: false
    },
    {
      name: 'Quantitative Surveying',
      value: 'Quantitative Surveying',
      checkbox: false
    },
    {
      name: 'Project Engg. & Mgmt.',
      value: 'Project Engg. & Mgmt.',
      checkbox: false
    },
    {
      name: 'Structural',
      value: 'Structural',
      checkbox: false
    },
    {
      name: 'Architecture',
      value: 'Architecture',
      checkbox: false
    },
    {
      name: 'Mech - Thermal',
      value: 'Mech - Thermal',
      checkbox: false
    },
    {
      name: 'Mech - Design',
      value: 'Mech - Design',
      checkbox: false
    },
    {
      name: 'Power Systems',
      value: 'Power Systems',
      checkbox: false
    },
    {
      name: 'Power Electronics & Drives',
      value: 'Power Electronics & Drives',
      checkbox: false
    },
    {
      name: 'Renewable Energy',
      value: 'Renewable Energy',
      checkbox: false
    },
    {
      name: 'Water Resources',
      value: 'Water Resources',
      checkbox: false
    },
    {
      name: 'Environmental',
      value: 'Environmental',
      checkbox: false
    },
    {
      name: 'Transportation Engg. & Mgmt',
      value: 'Transportation Engg. & Mgmt',
      checkbox: false
    },
    {
      name: 'Geotechnical',
      value: 'Geotechnical',
      checkbox: false
    },
    {
      name: 'Marine',
      value: 'Marine',
      checkbox: false
    },
  ],
  // Specialization
  specialization: [
    {
      name: 'Other',
      value: 'Other',
      checkbox: false
    },
    {
      name: 'Civil',
      value: 'Civil',
      checkbox: false
    },
    {
      name: 'Automobile',
      value: 'Automobile',
      checkbox: false
    },
    {
      name: 'Electrical',
      value: 'Electrical',
      checkbox: false
    },
    {
      name: 'Mining',
      value: 'Mining',
      checkbox: false
    },
    {
      name: 'Mechanical',
      value: 'Mechanical',
      checkbox: false
    }
  ],
  // Institute Names
  institutes: [
    { name: "Other", checkbox: false, value: "Other" },
    { name: "Indian Institute of Engineering Science And Technology, Shibpur", checkbox: false, value: "Indian Institute of Engineering Science And Technology, Shibpur" },
    { name: "Punjab Engineering College", checkbox: false, value: "Punjab Engineering College" },
    { name: "Jadavpur University", checkbox: false, value: "Jadavpur University" },
    { name: "College of Engineering, Pune", checkbox: false, value: "College of Engineering, Pune" },
    { name: "Veermata Jijabai Technological Institute, Mumbai", checkbox: false, value: "Veermata Jijabai Technological Institute, Mumbai" },
    { name: "Cochin University of Science and Technology", checkbox: false, value: "Cochin University of Science and Technology" },
    { name: "Jamia Millia Islamia, Delhi", checkbox: false, value: "Jamia Millia Islamia, Delhi" },
    { name: "Sardar Patel College of Engineering, Mumbai", checkbox: false, value: "Sardar Patel College of Engineering, Mumbai" },
    { name: "Birsa Institute of Technology, Sindri ", checkbox: false, value: "Birsa Institute of Technology, Sindri " },
    { name: "Jawaharlal Nehru Technological University, Kakinada", checkbox: false, value: "Jawaharlal Nehru Technological University, Kakinada" },
    { name: "Veer Surendra Sai University of Technology, Burla", checkbox: false, value: "Veer Surendra Sai University of Technology, Burla" },
    { name: "Andhra University College of Engineering", checkbox: false, value: "Andhra University College of Engineering" },
    { name: "Delhi Technological University", checkbox: false, value: "Delhi Technological University" },
    { name: "College Of Engineering, Guindy - Anna University", checkbox: false, value: "College Of Engineering, Guindy - Anna University" },
    { name: "PSG College of Technology, Coimbatore", checkbox: false, value: "PSG College of Technology, Coimbatore" },
    { name: "Jabalpur Engg College", checkbox: false, value: "Jabalpur Engg College" },
    { name: "Harcourt Butler Technical University", checkbox: false, value: "Harcourt Butler Technical University" },
    { name: "Osmania University", checkbox: false, value: "Osmania University" },
    { name: "Thiagarajar College of Engineering, Madurai", checkbox: false, value: "Thiagarajar College of Engineering, Madurai " },
    { name: "Indian Institute of Technology, Patna", checkbox: false, value: "Indian Institute of Technology, Patna" },
    { name: "Indian Institute of Technology, Tirupati", checkbox: false, value: "Indian Institute of Technology, Tirupati" },
    { name: "Indian Institute of Technology, Mandi", checkbox: false, value: "Indian Institute of Technology, Mandi" },
    { name: "Indian Institute of Technology, Gandhinagar", checkbox: false, value: "Indian Institute of Technology, Gandhinagar" },
    { name: "Indian Institute of Technology, Bhubaneswar", checkbox: false, value: "Indian Institute of Technology, Bhubaneswar" },
    { name: "Indian Institute of Technology, Indore", checkbox: false, value: "Indian Institute of Technology, Indore" },
    { name: "Indian Institute of Technology, Palakkad", checkbox: false, value: "Indian Institute of Technology, Palakkad" },
    { name: "Indian Institute of Technology, Jodhpur", checkbox: false, value: "Indian Institute of Technology, Jodhpur" },
    { name: "Indian Institute of Technology, Ropar", checkbox: false, value: "Indian Institute of Technology, Ropar" },
    { name: "Indian Institute of Technology, Bhilai", checkbox: false, value: "Indian Institute of Technology, Bhilai" },
    { name: "Indian Institute of Technology, Goa", checkbox: false, value: "Indian Institute of Technology, Goa" },
    { name: "Indian Institute of Technology, Jammu", checkbox: false, value: "Indian Institute of Technology, Jammu" },
    { name: "Indian Institute of Technology, Dharwad", checkbox: false, value: "Indian Institute of Technology, Dharwad" },
    { name: "National Institute of Technology, Durgapur", checkbox: false, value: "National Institute of Technology, Durgapur" },
    { name: "National Institute of Technology, Delhi", checkbox: false, value: "National Institute of Technology, Delhi" },
    { name: "National Institute of Technology, Trichy", checkbox: false, value: "National Institute of Technology, Trichy" },
    { name: "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar", checkbox: false, value: "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar" },
    { name: "National Institute of Technology, Jamshedpur", checkbox: false, value: "National Institute of Technology, Jamshedpur" },
    { name: "National Institute of Technology, Agartala", checkbox: false, value: "National Institute of Technology, Agartala" },
    { name: "National Institute of Technology, Warangal", checkbox: false, value: "National Institute of Technology, Warangal" },
    { name: "National Institute of Technology, Rourkela", checkbox: false, value: "National Institute of Technology, Rourkela" },
    { name: "Maulana Azad National Institute of Technology, Bhopal", checkbox: false, value: "Maulana Azad National Institute of Technology, Bhopal" },
    { name: "National Institute of Technology, Tadepalligudem, Andhra Pradesh", checkbox: false, value: "National Institute of Technology, Tadepalligudem, Andhra Pradesh" },
    { name: "Malaviya National Institute of Technology, Jaipur", checkbox: false, value: "Malaviya National Institute of Technology, Jaipur" },
    { name: "National Institute of Technology, Kurukshetra", checkbox: false, value: "National Institute of Technology, Kurukshetra" },
    { name: "National Institute of Technology, Silchar", checkbox: false, value: "National Institute of Technology, Silchar" },
    { name: "National Institute of Technology Mizoram", checkbox: false, value: "National Institute of Technology Mizoram" },
    { name: "National Institute of Technology, Meghalaya", checkbox: false, value: "National Institute of Technology, Meghalaya" },
    { name: "National Institute of Technology, Manipur", checkbox: false, value: "National Institute of Technology, Manipur" },
    { name: "National Institute of Technology, Goa", checkbox: false, value: "National Institute of Technology, Goa" },
    { name: "National Institute of Technology Karnataka, Surathkal", checkbox: false, value: "National Institute of Technology Karnataka, Surathkal" },
    { name: "Visvesvaraya National Institute of Technology, Nagpur", checkbox: false, value: "Visvesvaraya National Institute of Technology, Nagpur" },
    { name: "National Institute of Technology, Patna", checkbox: false, value: "National Institute of Technology, Patna" },
    { name: "S V National Institute of Technology, Surat", checkbox: false, value: "S V National Institute of Technology, Surat" },
    { name: "National Institute of Technology Uttarakhand", checkbox: false, value: "National Institute of Technology Uttarakhand" },
    { name: "National Institute of Technology, Srinagar", checkbox: false, value: "National Institute of Technology, Srinagar" },
    { name: "National Institute of Technology, Raipur", checkbox: false, value: "National Institute of Technology, Raipur" },
    { name: "National Institute of Technology Sikkim", checkbox: false, value: "National Institute of Technology Sikkim" },
    { name: "National Institute of Technology, Arunachal Pradesh", checkbox: false, value: "National Institute of Technology, Arunachal Pradesh" },
    { name: "National Institute of Technology, Nagaland", checkbox: false, value: "National Institute of Technology, Nagaland" },
    { name: "Motilal Nehru National Institute of Technology, Allahabad", checkbox: false, value: "Motilal Nehru National Institute of Technology, Allahabad" },
    { name: "National Institute of Technology, Calicut", checkbox: false, value: "National Institute of Technology, Calicut" },
    { name: "National Institute of Technology, Hamirpur", checkbox: false, value: "National Institute of Technology, Hamirpur" },
    { name: "National Institute of Technology, Karaikal", checkbox: false, value: "National Institute of Technology, Karaikal" },
    { name: "Birla Institute of Technology and Science, Pilani – Goa", checkbox: false, value: "Birla Institute of Technology and Science, Pilani – Goa" },
    { name: "Birla Institute of Technology & Science, Pilani - Hyderabad", checkbox: false, value: "Birla Institute of Technology & Science, Pilani - Hyderabad" },
    { name: "Birla Institute of Technology and Science, Pilani", checkbox: false, value: "Birla Institute of Technology and Science, Pilani" },
    { name: "Manipal Insitute of Technology", checkbox: false, value: "Manipal Insitute of Technology" },
    { name: "Thapar Institute of Engineering and Technology", checkbox: false, value: "Thapar Institute of Engineering and Technology" },
    { name: "Pondicherry Engg College", checkbox: false, value: "Pondicherry Engg College" },
    { name: "Birla Institute of Technology, Mesra", checkbox: false, value: "Birla Institute of Technology, Mesra" },
    { name: "Vellore Institute of Technology", checkbox: false, value: "Vellore Institute of Technology" },
    { name: "SRM Institute of Science and Technology", checkbox: false, value: "SRM Institute of Science and Technology" },
    { name: "Sri Sivasubramaniya Nadar (SSN) College of Engineering", checkbox: false, value: "Sri Sivasubramaniya Nadar (SSN) College of Engineering" },
    { name: "Amrita Vishwa Vidyapeetham University", checkbox: false, value: "Amrita Vishwa Vidyapeetham University" },
    { name: "Coimbatore Institute of Technology", checkbox: false, value: "Coimbatore Institute of Technology" },
    { name: "National Institute of Engineering, Mysore", checkbox: false, value: "National Institute of Engineering, Mysore" },
    { name: "Sastra University", checkbox: false, value: "Sastra University" },
    { name: "Walchand College of Engineering, Sangli", checkbox: false, value: "Walchand College of Engineering, Sangli" },
    { name: "Sri Jayachamarajendra College of Engineering", checkbox: false, value: "Sri Jayachamarajendra College of Engineering" },
    { name: "Birla Vishvakarma Mahavidyalaya Engineering College", checkbox: false, value: "Birla Vishvakarma Mahavidyalaya Engineering College" },
    { name: "University of Petroleum and Energy Studies (only for Civil & Safety)", checkbox: false, value: "University of Petroleum and Energy Studies (only for Civil & Safety)" },
    { name: "Rashtreeya Vidyalaya College of Engineering", checkbox: false, value: "Rashtreeya Vidyalaya College of Engineering" },
    { name: "Ramaiah Institute of Technology", checkbox: false, value: "Ramaiah Institute of Technology" },
    { name: "B.M.S. College of Engineering", checkbox: false, value: "B.M.S. College of Engineering" },
    { name: "Siddaganga Institute of Technology, Tumkur", checkbox: false, value: "Siddaganga Institute of Technology, Tumkur" },
    { name: "Bangalore Institute of Technology", checkbox: false, value: "Bangalore Institute of Technology" },
    { name: "Shiv Nadar University", checkbox: false, value: "Shiv Nadar University" },
    { name: "GMR Institute of Technology, Rajam", checkbox: false, value: "GMR Institute of Technology, Rajam" },
    { name: "Mahindra Ecole Centrale", checkbox: false, value: "Mahindra Ecole Centrale" },
    { name: "National Institute of Design", checkbox: false, value: "National Institute of Design" },
    { name: "Indian Statistical Institute", checkbox: false, value: "Indian Statistical Institute" },
    { name: "MIT, Pune", checkbox: false, value: "MIT, Pune" },
    { name: "Pearl Academy", checkbox: false, value: "Pearl Academy" },
    { name: "NMIMS", checkbox: false, value: "NMIMS" },
    { name: "Mumbai University", checkbox: false, value: "Mumbai University" },
    { name: "ISDI, Mumbai", checkbox: false, value: "ISDI, Mumbai" },
    { name: "Welingkar", checkbox: false, value: "Welingkar" },
    { name: "Sri Vidyanikethan Engineering College, Tirupati", checkbox: false, value: "Sri Vidyanikethan Engineering College, Tirupati" },
    { name: "Siddharth Institute of Engineering and Technology, Puttur   ", checkbox: false, value: "Siddharth Institute of Engineering and Technology, Puttur   " },
    { name: "Sri Venkateswara College of Engineering & Technology, Chittoor", checkbox: false, value: "Sri Venkateswara College of Engineering & Technology, Chittoor" },
    { name: "VEMU Institute of Technology, Chittoor", checkbox: false, value: "VEMU Institute of Technology, Chittoor" },
    { name: "MITS, Madanapalle", checkbox: false, value: "MITS, Madanapalle" },
    { name: "IIDT - Tirupati", checkbox: false, value: "IIDT - Tirupati" },
    { name: "Aditya Group of Educational Institutions", checkbox: false, value: "Aditya Group of Educational Institutions" },
    { name: "Pandit Deendayal Petroleum University", checkbox: false, value: "Pandit Deendayal Petroleum University" },
    { name: "Vignan University", checkbox: false, value: "Vignan University" },
    { name: "Koneru Lakshmaiah College of Engineering", checkbox: false, value: "Koneru Lakshmaiah College of Engineering" },
    { name: "Godavari Institute of Engineering and Technology", checkbox: false, value: "Godavari Institute of Engineering and Technology" },
    { name: "SPIT, Mumbai", checkbox: false, value: "SPIT, Mumbai" },
    { name: "Shri Ramdeobaba College Of Engineering And Management", checkbox: false, value: "Shri Ramdeobaba College Of Engineering And Management" },
    { name: "DJ Sanghvi, Mumbai", checkbox: false, value: "DJ Sanghvi, Mumbai" },
    { name: "PICT, Pune", checkbox: false, value: "PICT, Pune" },
    { name: "VIT, Pune", checkbox: false, value: "VIT, Pune" },
    { name: "Thadomal Shahani Engineering College", checkbox: false, value: "Thadomal Shahani Engineering College" },
    { name: "Fr Agnel, Bandra", checkbox: false, value: "Fr Agnel, Bandra" },
    { name: "Vivekanand , Mumbai", checkbox: false, value: "Vivekanand , Mumbai" },
    { name: "Maharshi Karve Stree Shikshan Samstha's Cummins College Of Engineering For Women", checkbox: false, value: "Maharshi Karve Stree Shikshan Samstha's Cummins College Of Engineering For Women" },
    { name: "Fr. Agnels, Vashi", checkbox: false, value: "Fr. Agnels, Vashi" },
    { name: "Zagdu Singh Charitable Trust's, Thakur College Of Engineering & Technology", checkbox: false, value: "Zagdu Singh Charitable Trust's, Thakur College Of Engineering & Technology" },
    { name: "Vishwakarma Institute of Information Technology VIIT Pune", checkbox: false, value: "Vishwakarma Institute of Information Technology VIIT Pune " },
    { name: "Government College Of Engineering, Amravati", checkbox: false, value: "Government College Of Engineering, Amravati" },
    { name: "Pune Vidhyarthi Griha's College Of Engineering And Technology", checkbox: false, value: "Pune Vidhyarthi Griha's College Of Engineering And Technology" },
    { name: "Shah And Anchor , Mumbai", checkbox: false, value: "Shah And Anchor , Mumbai" },
    { name: "The Bombay Salesian Society's Don Bosco Institute Of Technology (DBIT), Kurla", checkbox: false, value: "The Bombay Salesian Society's Don Bosco Institute Of Technology (DBIT), Kurla" },
    { name: "Shri Guru Gobind Singhji Institute Of Engineering & Technology", checkbox: false, value: "Shri Guru Gobind Singhji Institute Of Engineering & Technology" },
    { name: "Vidyalankar Institute of Technology", checkbox: false, value: "Vidyalankar Institute of Technology" },
    { name: "Pimpri Chinchwad Education Trust's Pimpri Chinchwad College Of Engineering", checkbox: false, value: "Pimpri Chinchwad Education Trust's Pimpri Chinchwad College Of Engineering" },
    { name: "St. Francis Institute of Technology", checkbox: false, value: "St. Francis Institute of Technology" },
    { name: "Ramrao Adik Institute of Technology, Nerul", checkbox: false, value: "Ramrao Adik Institute of Technology, Nerul" },
    { name: "Manjara Charitable Trust's, Rajiv Gandhi Institute Of Technology, Versova", checkbox: false, value: "Manjara Charitable Trust's, Rajiv Gandhi Institute Of Technology, Versova" },
    { name: "Government College of Engineering, Karad", checkbox: false, value: "Government College of Engineering, Karad" },
    { name: "South Indian Education Society's Graduate School of Technology, Navi Mumbai", checkbox: false, value: "South Indian Education Society's Graduate School of Technology, Navi Mumbai" },
    { name: "M.H. Saboo Siddik College Of Engineering, Byculla", checkbox: false, value: "M.H. Saboo Siddik College Of Engineering, Byculla" },
    { name: "Vidyavardhini College Of Engineering And Technology", checkbox: false, value: "Vidyavardhini College Of Engineering And Technology" },
    { name: "Atharva College of Engineering (ACE), Malad, Mumbai", checkbox: false, value: "Atharva College of Engineering (ACE), Malad, Mumbai" },
    { name: "Karmveer Kakasaheb Wagh Institute of Engineering Education & Research (K. K. Wagh)", checkbox: false, value: "Karmveer Kakasaheb Wagh Institute of Engineering Education & Research (K. K. Wagh)" },
    { name: "K. E. Society's Rajarambapu Institute of Technology, Walwa, Sangli", checkbox: false, value: "K. E. Society's Rajarambapu Institute of Technology, Walwa, Sangli" },
    { name: "Xavier Institute of Engineering, Mahim", checkbox: false, value: "Xavier Institute of Engineering, Mahim" },
    { name: "Yeshwantrao Chavan College Of Engineering", checkbox: false, value: "Yeshwantrao Chavan College Of Engineering" },
    { name: "Dattajirao Kadam Technology Education Society's Textile & Engineering Institute, Ichalkaranji", checkbox: false, value: "Dattajirao Kadam Technology Education Society's Textile & Engineering Institute, Ichalkaranji" },
    { name: "Dattajirao Kadam Technical Education Society's Textile & Engineering Institute, Ichalkaranji", checkbox: false, value: "Dattajirao Kadam Technical Education Society's Textile & Engineering Institute, Ichalkaranji" },
    { name: "Kolhapur Institute of Technology College of Engineering, Kolhapu", checkbox: false, value: "Kolhapur Institute of Technology College of Engineering, Kolhapu" },
    { name: "International Institute Of Information Technology, Pune (i2IT)", checkbox: false, value: "International Institute Of Information Technology, Pune (i2IT)" },
    { name: "G.H. Raisoni Group", checkbox: false, value: "G.H. Raisoni Group" },
    { name: "Ankush Shikshan Sanstha's G.H.Raisoni College of Engineering, Nagpur", checkbox: false, value: "Ankush Shikshan Sanstha's G.H.Raisoni College of Engineering, Nagpur" },
    { name: "Datta Meghe College of Engineering, Navi Mumbai", checkbox: false, value: "Datta Meghe College of Engineering, Navi Mumbai" },
    { name: " N.Y.S.S.'s Datta Meghe College of Engineering, Airoli, Navi Mumbai", checkbox: false, value: " N.Y.S.S.'s Datta Meghe College of Engineering, Airoli, Navi Mumbai" },
    { name: "Watumull Institute of Electronics Engineering & Computer Technology", checkbox: false, value: "Watumull Institute of Electronics Engineering & Computer Technology" },
    { name: "Progressive Education Society's Modern College Of Engineering", checkbox: false, value: "Progressive Education Society's Modern College Of Engineering" },
    { name: "Government College Of Engineering, Jalgaon", checkbox: false, value: "Government College Of Engineering, Jalgaon" },
    { name: "Rizvi College of Engineering", checkbox: false, value: "Rizvi College of Engineering" },
    { name: "Shree L.R. Tiwari College of Engineering, Mira Road, Mumbai", checkbox: false, value: "Shree L.R. Tiwari College of Engineering, Mira Road, Mumbai" },
    { name: "All India Shri Shivaji Memorial Society's College of Engineering, Pune", checkbox: false, value: "All India Shri Shivaji Memorial Society's College of Engineering, Pune" },
    { name: "Bharati Vidyapeeth's College Of Engineering, Mumbai", checkbox: false, value: "Bharati Vidyapeeth's College Of Engineering, Mumbai" },
    { name: "Pillai Institute of Information Technology, Engineering, Media Studies and Research, New Panvel", checkbox: false, value: "Pillai Institute of Information Technology, Engineering, Media Studies and Research, New Panvel" },
    { name: "Dr. Babasaheb Ambedkar Technological University, Lonere", checkbox: false, value: "Dr. Babasaheb Ambedkar Technological University, Lonere" },
    { name: "Shri Sant Gajanan Maharaj College of Engineering,Shegaon", checkbox: false, value: "Shri Sant Gajanan Maharaj College of Engineering,Shegaon " },
    { name: "Walchand Institute of Technology, Solapur", checkbox: false, value: "Walchand Institute of Technology, Solapur" },
    { name: "Dr. D. Y. Patil Pratishthan's D.Y.Patil College of Engineering Akurdi, Pune", checkbox: false, value: "Dr. D. Y. Patil Pratishthan's D.Y.Patil College of Engineering Akurdi, Pune" },
    { name: "All India Shri Shivaji Memorial Society's Institute of Information Technology,Pune", checkbox: false, value: "All India Shri Shivaji Memorial Society's Institute of Information Technology,Pune" },
    { name: "Terna Public Charitable Trust's, Terna Engineering College", checkbox: false, value: "Terna Public Charitable Trust's, Terna Engineering College" },
    { name: "Modern Education Society's Group of Colleges", checkbox: false, value: "Modern Education Society's Group of Colleges" },
    { name: "Modern Education Society's College of Engineering, Pune", checkbox: false, value: "Modern Education Society's College of Engineering, Pune" },
    { name: "Padmabhushan Vasantdada Patil Pratishthan's College of Engineering", checkbox: false, value: "Padmabhushan Vasantdada Patil Pratishthan's College of Engineering" },
    { name: "A. P. Shah Institute Of Technology", checkbox: false, value: "A. P. Shah Institute Of Technology" },
    { name: "Marathwada Mitra Mandal's Group", checkbox: false, value: "Marathwada Mitra Mandal's Group" },
    { name: "Mahatma Gandhi Mission Group", checkbox: false, value: "Mahatma Gandhi Mission Group" },
    { name: "Lokmanya Tilak Jankalyan Shikshan Sanstha's Lokmanya Tilak College Of Engineering", checkbox: false, value: "Lokmanya Tilak Jankalyan Shikshan Sanstha's Lokmanya Tilak College Of Engineering" },
    { name: "Bharati Vidyapeeth's College of Engineering for Women, Katraj, Dhankawadi, Pune", checkbox: false, value: "Bharati Vidyapeeth's College of Engineering for Women, Katraj, Dhankawadi, Pune" },
    { name: "Pad. Dr.D.Y.Patil Institute of Engineering, Management & Reseach, Akurdi, Pune", checkbox: false, value: "Pad. Dr.D.Y.Patil Institute of Engineering, Management & Reseach, Akurdi, Pune" },
    { name: "St. Vincent Pallotti College of Engineering & Technology, Nagpur", checkbox: false, value: "St. Vincent Pallotti College of Engineering & Technology, Nagpur" },
    { name: "Excelsior Education Society's K.C. College Of Engineering", checkbox: false, value: "Excelsior Education Society's K.C. College Of Engineering" },
    { name: "Nashik District Maratha Vidya Prasarak Samaj's Karmaveer Adv.Babaurao Ganpatrao Thakare College of Engineering, Nashik", checkbox: false, value: "Nashik District Maratha Vidya Prasarak Samaj's Karmaveer Adv.Babaurao Ganpatrao Thakare College of Engineering, Nashik" },
    { name: "Dr. D.Y. Patil Vidya Pratishthan Society's, Dr. D.Y. Patil Institute of Engineering & Technology, Pimpri", checkbox: false, value: "Dr. D.Y. Patil Vidya Pratishthan Society's, Dr. D.Y. Patil Institute of Engineering & Technology, Pimpri" },
    { name: "New Horizon Institute of Technology & Management, Thane", checkbox: false, value: "New Horizon Institute of Technology & Management, Thane" },
    { name: "Late Shri. Vishnu Waman Thakur Charitable Trust, Viva Institute of Technology, Shirgaon", checkbox: false, value: "Late Shri. Vishnu Waman Thakur Charitable Trust, Viva Institute of Technology, Shirgaon" },
    { name: "Sanjivani Rural Education Society's Sanjivani College of Engineering, Kopargaon", checkbox: false, value: "Sanjivani Rural Education Society's Sanjivani College of Engineering, Kopargaon" },
    { name: "Sanjivani Rural Education Society's Sanjivani College of Engineering, Kopargaon", checkbox: false, value: "Sanjivani Rural Education Society's Sanjivani College of Engineering, Kopargaon" },
    { name: "Dr. D. Y. Patil School OF Engineering, Lohegaon, Pune", checkbox: false, value: "Dr. D. Y. Patil School OF Engineering, Lohegaon, Pune" },
    { name: "Annasaheb Dange College of Engineering and Technology, Ashta, Sangli", checkbox: false, value: "Annasaheb Dange College of Engineering and Technology, Ashta, Sangli " },
    { name: "Jawahar Education Society's Annasaheb Chudaman Patil College Of Engineering", checkbox: false, value: "Jawahar Education Society's Annasaheb Chudaman Patil College Of Engineering" },
    { name: "Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati Dist.Pune", checkbox: false, value: "Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati Dist.Pune " },
    { name: "Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati Dist.Pune", checkbox: false, value: "Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati Dist.Pune" },
    { name: "Aldel Education Trust's St. John College of Engineering & Management, Vevoor, Palghar", checkbox: false, value: "Aldel Education Trust's St. John College of Engineering & Management, Vevoor, Palghar" },
    { name: "Prof. Ram Meghe Institute of Technology & Research, Amravati", checkbox: false, value: "Prof. Ram Meghe Institute of Technology & Research, Amravati " },
    { name: "Amrutvahini College Of Engineering, Sangamner", checkbox: false, value: "Amrutvahini College Of Engineering, Sangamner" },
    { name: "Saraswati Education Society's Saraswati College of Engineering,Kharghar Navi Mumbai", checkbox: false, value: "Saraswati Education Society's Saraswati College of Engineering,Kharghar Navi Mumbai" },
    { name: "Smt. Indira Gandhi College of Engineering, Navi Mumbai", checkbox: false, value: "Smt. Indira Gandhi College of Engineering, Navi Mumbai" },
    { name: "Universal College of Engineering,Kaman Dist. Thane", checkbox: false, value: "Universal College of Engineering,Kaman Dist. Thane" },
    { name: "M.G.M.'s College of Engineering and Technology, Kamothe, Navi Mumbai", checkbox: false, value: "M.G.M.'s College of Engineering and Technology, Kamothe, Navi Mumbai" },
    { name: "JSPM Narhe Technical Campus, Pune", checkbox: false, value: "JSPM Narhe Technical Campus, Pune" },
    { name: "Dr. J. J. Magdum Charitable Trust's Dr. J.J. Magdum College of Engineering, Jaysingpur", checkbox: false, value: "Dr. J. J. Magdum Charitable Trust's Dr. J.J. Magdum College of Engineering, Jaysingpur " },
    { name: "Sou. Sushila Danchand Ghodawat Cha.Trust's Sanjay Ghodavat Group of Institution (Integrated Campus), Atigre, Kolhapur", checkbox: false, value: "Sou. Sushila Danchand Ghodawat Cha.Trust's Sanjay Ghodavat Group of Institution (Integrated Campus), Atigre, Kolhapur" },
    { name: "Sir Shantilal Badjate Charitable Trust's S. B. Jain Institute of technology, Management & Research, Nagpur", checkbox: false, value: "Sir Shantilal Badjate Charitable Trust's S. B. Jain Institute of technology, Management & Research, Nagpur " },
    { name: "Pradnya Niketan Education Society's Nagesh Karajagi Orchid College of Engineering & Technology, Solapur", checkbox: false, value: "Pradnya Niketan Education Society's Nagesh Karajagi Orchid College of Engineering & Technology, Solapur" },
    { name: "MET Bhujbal Knowledge City MET League's Engineering College, Adgaon, Nashik", checkbox: false, value: "MET Bhujbal Knowledge City MET League's Engineering College, Adgaon, Nashik" },
    { name: "Bharati Vidyapeeth's College of Engineering,Lavale, Pune", checkbox: false, value: "Bharati Vidyapeeth's College of Engineering,Lavale, Pune " },
    { name: "Shivajirao S. Jondhale College of Engineering, Dombivali,Mumbai", checkbox: false, value: "Shivajirao S. Jondhale College of Engineering, Dombivali,Mumbai" },
    { name: "Zeal Education Society's Zeal College of Engineering & Reserch, Narhe, Pune", checkbox: false, value: "Zeal Education Society's Zeal College of Engineering & Reserch, Narhe, Pune " },
    { name: "Samridhi Sarwajanik Charitable Trust, Jhulelal Institute of Technology, Nagpur", checkbox: false, value: "Samridhi Sarwajanik Charitable Trust, Jhulelal Institute of Technology, Nagpur" },
    { name: "Gokhale Education Society's, R.H. Sapat College of Engineering, Management Studies and Research, Nashik", checkbox: false, value: "Gokhale Education Society's, R.H. Sapat College of Engineering, Management Studies and Research, Nashik" },
    { name: "Sandip Foundation, Sandip Institute of Technology and Research Centre, Mahiravani, Nashik", checkbox: false, value: "Sandip Foundation, Sandip Institute of Technology and Research Centre, Mahiravani, Nashik" },
    { name: "Anjuman-I-Islam's Kalsekar Technical Campus", checkbox: false, value: "Anjuman-I-Islam's Kalsekar Technical Campus" },
    { name: "Nutan Maharashtra Institute of Engineering and Technology", checkbox: false, value: "Nutan Maharashtra Institute of Engineering and Technology" },
    { name: "Mahatma Education Society's Pillai HOC College of Engineering & Technology, Tal. Khalapur. Dist. Raigad", checkbox: false, value: "Mahatma Education Society's Pillai HOC College of Engineering & Technology, Tal. Khalapur. Dist. Raigad" },
    { name: "Sipna Shikshan Prasarak Mandal College of Engineering & Technology, Amravati", checkbox: false, value: "Sipna Shikshan Prasarak Mandal College of Engineering & Technology, Amravati " },
    { name: "Department of Technology, Shivaji University, Kolhapur", checkbox: false, value: "Department of Technology, Shivaji University, Kolhapur" },
    { name: "Indira College of Engineering & Management, Pune", checkbox: false, value: "Indira College of Engineering & Management, Pune" },
    { name: "Mauli Group of Institutions, College of Engineering and Technology, Shegaon", checkbox: false, value: "Mauli Group of Institutions, College of Engineering and Technology, Shegaon" },
    { name: "Shri Vithal Education and Research Institute's College of Engineering, Pandharpur", checkbox: false, value: "Shri Vithal Education and Research Institute's College of Engineering, Pandharpur" },
    { name: "Dr. D. Y. Patil School of Engineering & Technology, Charholi(Bk), Via Lohgaon, Pune", checkbox: false, value: "Dr. D. Y. Patil School of Engineering & Technology, Charholi(Bk), Via Lohgaon, Pune" },
    { name: "Rajiv Gandhi College of Engineering & Research, Hingna Road, Nagpur", checkbox: false, value: "Rajiv Gandhi College of Engineering & Research, Hingna Road, Nagpur" },
    { name: "P. R. Pote (Patil) Education & Welfare Trust's Group of Institution(Integrated Campus), Amravati", checkbox: false, value: "P. R. Pote (Patil) Education & Welfare Trust's Group of Institution(Integrated Campus), Amravati " },
    { name: "Marathwada Mitra Mandal's Institute of Technology, Lohgaon, Pune", checkbox: false, value: "Marathwada Mitra Mandal's Institute of Technology, Lohgaon, Pune" },
    { name: "Cummins College of Engineering For Women, Sukhali (Gupchup), Tal. Hingna Hingna Nagpur", checkbox: false, value: "Cummins College of Engineering For Women, Sukhali (Gupchup), Tal. Hingna Hingna Nagpur" },
    { name: "Lokmanya Tilak Jankalyan Shikshan Sanstha, Priyadarshani College of Engineering, Nagpur", checkbox: false, value: "Lokmanya Tilak Jankalyan Shikshan Sanstha, Priyadarshani College of Engineering, Nagpur" },
    { name: "Gharda Foundation's Gharda Institute of Technology,Khed, Ratnagiri", checkbox: false, value: "Gharda Foundation's Gharda Institute of Technology,Khed, Ratnagiri" },
    { name: "Shetkari Shikshan Mandal's Pad. Vasantraodada Patil Institute of Technology, Budhgaon, Sangli", checkbox: false, value: "Shetkari Shikshan Mandal's Pad. Vasantraodada Patil Institute of Technology, Budhgaon, Sangli " },
    { name: "SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering, (Jain Gurukul), Neminagar,Chandwad,(Nashik)", checkbox: false, value: "SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering, (Jain Gurukul), Neminagar,Chandwad,(Nashik)" },
    { name: "G.H. Raisoni Academy of Engineering & Technology, Nagpur", checkbox: false, value: "G.H. Raisoni Academy of Engineering & Technology, Nagpur" },
    { name: "Hope Foundation and research center's Finolex Academy of Management and Technology, Ratnagiri", checkbox: false, value: "Hope Foundation and research center's Finolex Academy of Management and Technology, Ratnagiri" },
    { name: "S.S.P.M.'s College of Engineering, Kankavli", checkbox: false, value: "S.S.P.M.'s College of Engineering, Kankavli " },
    { name: "S.S.P.M.'s College of Engineering, Kankavli", checkbox: false, value: "S.S.P.M.'s College of Engineering, Kankavli" },
    { name: "S. B. Patil College Of Engineering", checkbox: false, value: "S. B. Patil College Of Engineering" },
    { name: "Institute of Knowledge College Of Engineering", checkbox: false, value: "Institute of Knowledge College Of Engineering" },
    { name: "Government College Of Technology, Coimbatore", checkbox: false, value: "Government College Of Technology, Coimbatore" },
    { name: "SVCOE, Chennai", checkbox: false, value: "SVCOE, Chennai" },
    { name: "Kumaraguru College Of Technology", checkbox: false, value: "Kumaraguru College Of Technology" },
    { name: "Government College Of Engineering, Salem", checkbox: false, value: "Government College Of Engineering, Salem" },
    { name: "R.M.K. COLLEGE OF ENGINEERING AND TECHNOLOGY (Group)", checkbox: false, value: "R.M.K. COLLEGE OF ENGINEERING AND TECHNOLOGY (Group)" },
    { name: "SRI KRISHNA COLLEGE OF ENGINEERING & TECHNOLOGY", checkbox: false, value: "SRI KRISHNA COLLEGE OF ENGINEERING & TECHNOLOGY " },
    { name: "Meenakshi Sundararajan Engineering College", checkbox: false, value: "Meenakshi Sundararajan Engineering College" },
    { name: "SRM Easwari Engineering College", checkbox: false, value: "SRM Easwari Engineering College" },
    { name: "Mepco Schlenk Engineering College", checkbox: false, value: "Mepco Schlenk Engineering College" },
    { name: "Loyola-ICAM College of Engineering and Technology", checkbox: false, value: "Loyola-ICAM College of Engineering and Technology" },
    { name: "Kongu Engineering College", checkbox: false, value: "Kongu Engineering College" },
    { name: "Panimalar Engineering College, Chennai", checkbox: false, value: "Panimalar Engineering College, Chennai" },
    { name: "Sri Ramakrishna Engineering College", checkbox: false, value: "Sri Ramakrishna Engineering College" },
    { name: "Bannari Amman Institute of Technology, Erode", checkbox: false, value: "Bannari Amman Institute of Technology, Erode" },
    { name: "VELAMMAL ENGINEERING COLLEGE", checkbox: false, value: "VELAMMAL ENGINEERING COLLEGE" },
    { name: "RAJALAKSHMI ENGINEERING COLLEGE", checkbox: false, value: "RAJALAKSHMI ENGINEERING COLLEGE" },
    { name: "JEPPIAAR ENGINEERING COLLEGE", checkbox: false, value: "JEPPIAAR ENGINEERING COLLEGE" },
    { name: "Dr.Mahalingam College Of Engineering And Technology", checkbox: false, value: "Dr.Mahalingam College Of Engineering And Technology" },
    { name: "Sri Sai Ram Group of Colleges", checkbox: false, value: "Sri Sai Ram Group of Colleges" },
    { name: "SRI KRISHNA COLLEGE OF TECHNOLOGY", checkbox: false, value: "SRI KRISHNA COLLEGE OF TECHNOLOGY" },
    { name: "VLB Group of Institutions", checkbox: false, value: "VLB Group of Institutions" },
    { name: "Government College of Engineering, Bargur", checkbox: false, value: "Government College of Engineering, Bargur" },
    { name: "Valliammai Engineering College", checkbox: false, value: "Valliammai Engineering College" },
    { name: "Sona College Of Technology", checkbox: false, value: "Sona College Of Technology" },
    { name: "Karpagam Group of Colleges", checkbox: false, value: "Karpagam Group of Colleges" },
    { name: "Prince Shri Venkateshwara Padmawathy Engineering College ", checkbox: false, value: "Prince Shri Venkateshwara Padmawathy Engineering College  " },
    { name: " JEPPIAAR INSTITUTE OF TECHNOLOGY", checkbox: false, value: " JEPPIAAR INSTITUTE OF TECHNOLOGY" },
    { name: " RAJALAKSHMI INSTITUTE OF TECHNOLOGY", checkbox: false, value: " RAJALAKSHMI INSTITUTE OF TECHNOLOGY" },
    { name: "Sri Shakthi Institutions Group", checkbox: false, value: "Sri Shakthi Institutions Group" },
    { name: "Saveetha Engineering College", checkbox: false, value: "Saveetha Engineering College" },
    { name: "KPR Institute Of Engineering And Technology", checkbox: false, value: "KPR Institute Of Engineering And Technology" },
    { name: "Misrimal Navajee Munoth Jain Engineering College", checkbox: false, value: "Misrimal Navajee Munoth Jain Engineering College" },
    { name: "KCG College of Technology", checkbox: false, value: "KCG College of Technology" },
    { name: "VTMT Dr R Rangarajan Dr R Sakunthala Engineering College, Avadi", checkbox: false, value: "VTMT Dr R Rangarajan Dr R Sakunthala Engineering College, Avadi" },
    { name: "Sri Ramakrishna Institute Of Technology", checkbox: false, value: "Sri Ramakrishna Institute Of Technology" },
    { name: "Meenakshi College Of Engineering", checkbox: false, value: "Meenakshi College Of Engineering" },
    { name: "VSB College of Engineering Technical Campus", checkbox: false, value: "VSB College of Engineering Technical Campus" },
    { name: "Sri Eshwar College Of Engineering", checkbox: false, value: "Sri Eshwar College Of Engineering" },
    { name: "JEPPIAAR SRR ENGINEERING COLLEGE", checkbox: false, value: "JEPPIAAR SRR ENGINEERING COLLEGE" },
    { name: "SVS College Of Engineering", checkbox: false, value: "SVS College Of Engineering" },
    { name: "Annamalai University", checkbox: false, value: "Annamalai University" },
    { name: "Dr.N.G.P. Institute of Technology", checkbox: false, value: "Dr.N.G.P. Institute of Technology" },
    { name: "Veltech Multi Tech Dr Rangarajan Dr Sakunthala Engineering College, Chennai", checkbox: false, value: "Veltech Multi Tech Dr Rangarajan Dr Sakunthala Engineering College, Chennai" },
    { name: "Jerusalem College of Engineering", checkbox: false, value: "Jerusalem College of Engineering" },
    { name: "SriGuru Institute of Technology", checkbox: false, value: "SriGuru Institute of Technology" },
    { name: "HINDUSTHAN COLLEGE OF ENGINEERING AND TECHNOLOGY", checkbox: false, value: "HINDUSTHAN COLLEGE OF ENGINEERING AND TECHNOLOGY" },
    { name: "PA Engineering College", checkbox: false, value: "PA Engineering College " },
    { name: "S.A.Engineering College", checkbox: false, value: "S.A.Engineering College" },
    { name: "Agni College of Technology", checkbox: false, value: "Agni College of Technology" },
    { name: "Adhiyamaan College of Engineering", checkbox: false, value: "Adhiyamaan College of Engineering" },
    { name: "SNS Institutions Group", checkbox: false, value: "SNS Institutions Group" },
    { name: "JEPPIAAR MAAMALLAN ENGINEERING COLLEGE", checkbox: false, value: "JEPPIAAR MAAMALLAN ENGINEERING COLLEGE" },
    { name: "KANCHEEPURAM", checkbox: false, value: "KANCHEEPURAM" },
    { name: "Park College of Engineering", checkbox: false, value: "Park College of Engineering" },
    { name: "Park College of Engineering And Technology", checkbox: false, value: "Park College of Engineering And Technology" },
    { name: "KGiSL Institute of Technology", checkbox: false, value: "KGiSL Institute of Technology" },
    { name: "Adhiparasakthi Engineering College, Melmaruvathur", checkbox: false, value: "Adhiparasakthi Engineering College, Melmaruvathur" },
    { name: "Kalaignar Karunanidhi Institute Of Technology", checkbox: false, value: "Kalaignar Karunanidhi Institute Of Technology" },
    { name: "Akshaya College Of Engineering And Technology", checkbox: false, value: "Akshaya College Of Engineering And Technology" },
    { name: "HINDUSTHAN INSTITUTE OF TECHNOLOGY", checkbox: false, value: "HINDUSTHAN INSTITUTE OF TECHNOLOGY" },
    { name: "Jaya Engineering College", checkbox: false, value: "Jaya Engineering College" },
    { name: "Anand Institute Of Higher Technology", checkbox: false, value: "Anand Institute Of Higher Technology" },
    { name: "Nehru Institute of Engineering and Technology", checkbox: false, value: "Nehru Institute of Engineering and Technology" },
    { name: "Coimbatore Institute Of Engineering And Technology", checkbox: false, value: "Coimbatore Institute Of Engineering And Technology" },
    { name: "Sasurie Group of Colleges", checkbox: false, value: "Sasurie Group of Colleges" },
    { name: "Krishnasamy College of Engineering and Technology", checkbox: false, value: "Krishnasamy College of Engineering and Technology" },
    { name: "RVS College of Engineering & Technology", checkbox: false, value: "RVS College of Engineering & Technology" },
    { name: "Dhanalakshmi College of Engineering", checkbox: false, value: "Dhanalakshmi College of Engineering" },
    { name: "Tagore Engineering College", checkbox: false, value: "Tagore Engineering College" },
    { name: "New Prince Shri Bhavani College Of Engg & Tech", checkbox: false, value: "New Prince Shri Bhavani College Of Engg & Tech" },
    { name: "United Institute Of Technology", checkbox: false, value: "United Institute Of Technology" },
    { name: "DMI College of Engineering", checkbox: false, value: "DMI College of Engineering" },
    { name: "PPG Institute of Technology", checkbox: false, value: "PPG Institute of Technology" },
    { name: "GKM College of Engineering and Technology", checkbox: false, value: "GKM College of Engineering and Technology" },
    { name: "Pallavan College of Engineering", checkbox: false, value: "Pallavan College of Engineering" },
    { name: "Sree Sastha Institute of Engineering and Technology", checkbox: false, value: "Sree Sastha Institute of Engineering and Technology" },
    { name: "Karpaga Vinayaga Educational Group", checkbox: false, value: "Karpaga Vinayaga Educational Group" },
    { name: "Sri Muthukumaran Institute of Technology", checkbox: false, value: "Sri Muthukumaran Institute of Technology" },
    { name: "Maharaja Engineering College", checkbox: false, value: "Maharaja Engineering College" },
    { name: "Srinivasa Institute of Engineering and Technology", checkbox: false, value: "Srinivasa Institute of Engineering and Technology" },
    { name: "Adithya Institute of Technology, Coimbatore", checkbox: false, value: "Adithya Institute of Technology, Coimbatore" },
    { name: "Thangavelu Engineering College", checkbox: false, value: "Thangavelu Engineering College" },
    { name: "University Visveswariah College Of Engineering (UVCE)", checkbox: false, value: "University Visveswariah College Of Engineering (UVCE)" },
    { name: "National Institute of Engineering, Institute Of Technology, Mysore", checkbox: false, value: "National Institute of Engineering, Institute Of Technology, Mysore" },
    { name: "BMSCE, Bangalore", checkbox: false, value: "BMSCE, Bangalore" },
    { name: "Dayananda Sagar College of Engineering", checkbox: false, value: "Dayananda Sagar College of Engineering" },
    { name: "Sir Mokshagundam Visvesvaraya Institute of Technology (MVIT)", checkbox: false, value: "Sir Mokshagundam Visvesvaraya Institute of Technology (MVIT)" },
    { name: "RNS Institute Of Technology, Bangalore (RNSIT)", checkbox: false, value: "RNS Institute Of Technology, Bangalore (RNSIT)" },
    { name: "B.N.M Institute Of Technology (BNMIT)", checkbox: false, value: "B.N.M Institute Of Technology (BNMIT)" },
    { name: "PESIT, Bangalore ", checkbox: false, value: "PESIT, Bangalore  " },
    { name: "Nitte Meenakshi Institute of Technology, Bangalore", checkbox: false, value: "Nitte Meenakshi Institute of Technology, Bangalore" },
    { name: "Dr. Ambedkar Institute Of Technology", checkbox: false, value: "Dr. Ambedkar Institute Of Technology" },
    { name: "JSS Academy Of Technical Education, Bangalore", checkbox: false, value: "JSS Academy Of Technical Education, Bangalore" },
    { name: "CMRIT College of Engineering, Bangalore", checkbox: false, value: "CMRIT College of Engineering, Bangalore" },
    { name: "Karnatak Law Society’s Gogte Institute of Technology, Belagavi", checkbox: false, value: "Karnatak Law Society’s Gogte Institute of Technology, Belagavi" },
    { name: "New Horizon College Of Engineering (NHCE)", checkbox: false, value: "New Horizon College Of Engineering (NHCE)" },
    { name: "St. Joseph Engineering College", checkbox: false, value: "St. Joseph Engineering College" },
    { name: "Acharya Institute Of Technology", checkbox: false, value: "Acharya Institute Of Technology" },
    { name: "Vidya Vardhaka College of Engineering Mysuru", checkbox: false, value: "Vidya Vardhaka College of Engineering Mysuru" },
    { name: "SJB Institute of Technology", checkbox: false, value: "SJB Institute of Technology" },
    { name: "Sahyadri College Of Engineering & Management, Mangalore", checkbox: false, value: "Sahyadri College Of Engineering & Management, Mangalore" },
    { name: "KLE Dr M. S. Sheshagiri College of Engineering, Belgaum", checkbox: false, value: "KLE Dr M. S. Sheshagiri College of Engineering, Belgaum" },
    { name: "Bapuji Institute Of Engineering & Technology", checkbox: false, value: "Bapuji Institute Of Engineering & Technology" },
    { name: "Global Academy Of Technology (GAT)", checkbox: false, value: "Global Academy Of Technology (GAT)" },
    { name: "PES College of Engineering, Mandya", checkbox: false, value: "PES College of Engineering, Mandya" },
    { name: "MVJ College Of Engineering", checkbox: false, value: "MVJ College Of Engineering" },
    { name: "Saptagiri College Of Engineering (SCE)", checkbox: false, value: "Saptagiri College Of Engineering (SCE)" },
    { name: "Reva Institute Of  Technology & Management", checkbox: false, value: "Reva Institute Of  Technology & Management" },
    { name: "Poojya Dodappa Appa College of Engineering", checkbox: false, value: "Poojya Dodappa Appa College of Engineering" },
    { name: "Kammavari Sangham Institute Of Technology (KSIT)", checkbox: false, value: "Kammavari Sangham Institute Of Technology (KSIT)" },
    { name: "SJC Institute Of Technology, Chickaballapur", checkbox: false, value: "SJC Institute Of Technology, Chickaballapur" },
    { name: "Cambridge Institute Of Technology", checkbox: false, value: "Cambridge Institute Of Technology" },
    { name: "Mangalore Institute Of Technology & Engineering, Mangalore", checkbox: false, value: "Mangalore Institute Of Technology & Engineering, Mangalore" },
    { name: "Sai Vidya Institute Of Technology", checkbox: false, value: "Sai Vidya Institute Of Technology" },
    { name: "GSSS Institute Of Engineering & Technology For Women, Mysore", checkbox: false, value: "GSSS Institute Of Engineering & Technology For Women, Mysore" },
    { name: "Sri Siddhartha Institute of Technology", checkbox: false, value: "Sri Siddhartha Institute of Technology" },
    { name: "Oxford College Of Engineering", checkbox: false, value: "Oxford College Of Engineering" },
    { name: "Don Bosco Institute of Technology, Bangalore", checkbox: false, value: "Don Bosco Institute of Technology, Bangalore" },
    { name: "Atria Institute Of Technology", checkbox: false, value: "Atria Institute Of Technology" },
    { name: "Canara Engineering College, Mangalore", checkbox: false, value: "Canara Engineering College, Mangalore" },
    { name: "Sri Venkateswara College Of Engineering", checkbox: false, value: "Sri Venkateswara College Of Engineering" },
    { name: "Channabasaveshwara Institute of Technology (CIT, Tumkur)", checkbox: false, value: "Channabasaveshwara Institute of Technology (CIT, Tumkur)" },
    { name: "Vemana Institute Of Technology", checkbox: false, value: "Vemana Institute Of Technology" },
    { name: "Vidya Vikas Institute Of Engineering & Technology, Mysore", checkbox: false, value: "Vidya Vikas Institute Of Engineering & Technology, Mysore" },
    { name: "RajaRajeswari College of Engineering", checkbox: false, value: "RajaRajeswari College of Engineering" },
    { name: "Nagarjuna College of Engineering & Technology", checkbox: false, value: "Nagarjuna College of Engineering & Technology" },
    { name: "AMC Engineering College", checkbox: false, value: "AMC Engineering College" },
    { name: "East West Institute Of Technology", checkbox: false, value: "East West Institute Of Technology" },
    { name: "Shri Dharmasthala Manjunatheshwara College of engineering & Technology (SDM)", checkbox: false, value: "Shri Dharmasthala Manjunatheshwara College of engineering & Technology (SDM)" },
    { name: "APS College Of Engineering", checkbox: false, value: "APS College Of Engineering" },
    { name: "HKBK College Of Engineering", checkbox: false, value: "HKBK College Of Engineering" },
    { name: "Alva`s Institute Of Engineering And Technology, Moodbidri", checkbox: false, value: "Alva`s Institute Of Engineering And Technology, Moodbidri" },
    { name: "Hirasugar Institute of Technology", checkbox: false, value: "Hirasugar Institute of Technology" },
    { name: "P. A. College Of Engineering, Mangalore", checkbox: false, value: "P. A. College Of Engineering, Mangalore" },
    { name: "Vivekananda College Of Engineering And Technology, Puttur", checkbox: false, value: "Vivekananda College Of Engineering And Technology, Puttur" },
    { name: "Alpha College Of Engineering", checkbox: false, value: "Alpha College Of Engineering" },
    { name: "Coorg Institute Of Technology, Ponnampet", checkbox: false, value: "Coorg Institute Of Technology, Ponnampet" },
    { name: "KVG College of Engineering", checkbox: false, value: "KVG College of Engineering" },
    { name: "R L Jalappa Institute of Technology, Bangalore", checkbox: false, value: "R L Jalappa Institute of Technology, Bangalore" },
    { name: "Maharaja Institute Of Technology, Mysore", checkbox: false, value: "Maharaja Institute Of Technology, Mysore" },
    { name: "Sambhram Institute Of Technology", checkbox: false, value: "Sambhram Institute Of Technology" },
    { name: "Rajiv Gandhi Institute Of Technology", checkbox: false, value: "Rajiv Gandhi Institute Of Technology" },
    { name: "East Point College Of Engineering And Technology", checkbox: false, value: "East Point College Of Engineering And Technology" },
    { name: "Sri Krishna Institute Of Technology", checkbox: false, value: "Sri Krishna Institute Of Technology" },
    { name: "City Engineering College", checkbox: false, value: "City Engineering College" },
    { name: "Angadi Institute of Technology and Management", checkbox: false, value: "Angadi Institute of Technology and Management" },
    { name: "BTL Institute of Technology", checkbox: false, value: "BTL Institute of Technology" },
    { name: "Jnana Vikas Institute Of Technology", checkbox: false, value: "Jnana Vikas Institute Of Technology" },
    { name: "Shree Devi Group of Institutions", checkbox: false, value: "Shree Devi Group of Institutions" },
    { name: "Brindavan College Of Engineering", checkbox: false, value: "Brindavan College Of Engineering" },
    { name: "Shirdi Sai Engineering College, Bangalore", checkbox: false, value: "Shirdi Sai Engineering College, Bangalore" },
    { name: "Sri Taralabalu Jagadguru Institute of Technology", checkbox: false, value: "Sri Taralabalu Jagadguru Institute of Technology" },
    { name: "Rajeev Institute of Technology", checkbox: false, value: "Rajeev Institute of Technology" },
    { name: "Dr. T Thimaiah Institute Of Technology", checkbox: false, value: "Dr. T Thimaiah Institute Of Technology" },
    { name: "Bheemanna Khandre Institute of Technology( Formerly REC), Karnataka", checkbox: false, value: "Bheemanna Khandre Institute of Technology( Formerly REC), Karnataka" },
    { name: "JNTUH", checkbox: false, value: "JNTUH" },
    { name: "IIIT Hyderabad", checkbox: false, value: "IIIT Hyderabad" },
    { name: "Chaitanya Bharathi Institute of Technology", checkbox: false, value: "Chaitanya Bharathi Institute of Technology" },
    { name: "Vasavi College of Engineering, Hyderabad", checkbox: false, value: "Vasavi College of Engineering, Hyderabad" },
    { name: "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering &Technology", checkbox: false, value: "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering &Technology" },
    { name: "Mahatma Gandhi Institute of Technology", checkbox: false, value: "Mahatma Gandhi Institute of Technology" },
    { name: "Gokaraju Rangaraju Institute of Engineering and Technology", checkbox: false, value: "Gokaraju Rangaraju Institute of Engineering and Technology" },
    { name: "CVR College of Engineering", checkbox: false, value: "CVR College of Engineering" },
    { name: "Vardhaman College of Engineering", checkbox: false, value: "Vardhaman College of Engineering" },
    { name: "B.V. Raju Institute of Technology ", checkbox: false, value: "B.V. Raju Institute of Technology " },
    { name: "Bvrit Hyderabad College of Engineering for Women", checkbox: false, value: "Bvrit Hyderabad College of Engineering for Women" },
    { name: "Anurag Group of Institutions", checkbox: false, value: "Anurag Group of Institutions" },
    { name: "CMR College of Engineering & Technology", checkbox: false, value: "CMR College of Engineering & Technology" },
    { name: "Institute of Aeronautical Engineering, Dundigal", checkbox: false, value: "Institute of Aeronautical Engineering, Dundigal" },
    { name: "Guru Nanak Institutions Technical Campus", checkbox: false, value: "Guru Nanak Institutions Technical Campus" },
    { name: "MLR Institute of Technology", checkbox: false, value: "MLR Institute of Technology" },
    { name: "Malla Reddy Engineering College", checkbox: false, value: "Malla Reddy Engineering College " },
    { name: "Aditya Engineering College", checkbox: false, value: "Aditya Engineering College" },
    { name: "University Of Calcutta", checkbox: false, value: "University Of Calcutta" },
    { name: "Kalyani Goverment Engineering College,Kalyani,Nadia", checkbox: false, value: "Kalyani Goverment Engineering College,Kalyani,Nadia" },
    { name: "Maulana Abul Kalam Azad University Of Technology", checkbox: false, value: "Maulana Abul Kalam Azad University Of Technology" },
    { name: "Institute Of Engineering & Management, Salt Lake", checkbox: false, value: "Institute Of Engineering & Management, Salt Lake" },
    { name: "Heritage Institute Of Technology, Kolkata", checkbox: false, value: "Heritage Institute Of Technology, Kolkata" },
    { name: "Aliah University, New Town", checkbox: false, value: "Aliah University, New Town" },
    { name: "Government College Of Engineering And Leather Technology, Kolkata", checkbox: false, value: "Government College Of Engineering And Leather Technology, Kolkata" },
    { name: "Jalpaiguri Goverment Engineering College ,Jalpaiguri", checkbox: false, value: "Jalpaiguri Goverment Engineering College ,Jalpaiguri" },
    { name: "Govt. College Of Engineering & Ceramic Technology, Kolkata", checkbox: false, value: "Govt. College Of Engineering & Ceramic Technology, Kolkata" },
    { name: "Techno India-Salt Lake, Sector-V, Salt Lake", checkbox: false, value: "Techno India-Salt Lake, Sector-V, Salt Lake" },
    { name: "Govt. College Of Engineering & Textile Technology, Serampore", checkbox: false, value: "Govt. College Of Engineering & Textile Technology, Serampore" },
    { name: "Indian Institute of Engineering Science and Technology", checkbox: false, value: "Indian Institute of Engineering Science and Technology" },
    { name: "Haldia Institute of Technology", checkbox: false, value: "Haldia Institute of Technology" },
    { name: "University Institute Of Technology, Burdwan", checkbox: false, value: "University Institute Of Technology, Burdwan" },
    { name: "St. Thomas College Of Engineering & Technology, Khidirpur, Kolkata", checkbox: false, value: "St. Thomas College Of Engineering & Technology, Khidirpur, Kolkata" },
    { name: "RCC Institute Of Information Technology, Kolkata", checkbox: false, value: "RCC Institute Of Information Technology, Kolkata" },
    { name: "Ramkrishna Mahato Government Engineering College, Purulia (Earlier Purulia Government Engineering College, Purulia)", checkbox: false, value: "Ramkrishna Mahato Government Engineering College, Purulia (Earlier Purulia Government Engineering College, Purulia)" },
    { name: "Netaji Subhas Engineering College, Garia, Kolkata", checkbox: false, value: "Netaji Subhas Engineering College, Garia, Kolkata" },
    { name: "Cooch Behar Government Engineering College, Cooch Behar", checkbox: false, value: "Cooch Behar Government Engineering College, Cooch Behar" },
    { name: "Academy Of Technology, Adisaptagram, Hooghly", checkbox: false, value: "Academy Of Technology, Adisaptagram, Hooghly" },
    { name: "B.P. Poddar Institute Of Management & Technology, Kolkata", checkbox: false, value: "B.P. Poddar Institute Of Management & Technology, Kolkata" },
    { name: "Modern Institute Of Engineering & Technology,Bandel,Hooghly", checkbox: false, value: "Modern Institute Of Engineering & Technology,Bandel,Hooghly" },
    { name: "Meghnad Saha Institute Of Technology, Kolkata", checkbox: false, value: "Meghnad Saha Institute Of Technology, Kolkata" },
    { name: "Techno India College Of Technology, Rajarhat, New Town", checkbox: false, value: "Techno India College Of Technology, Rajarhat, New Town" },
    { name: "Future Institute Of Engineering & Management,Sonarpur", checkbox: false, value: "Future Institute Of Engineering & Management,Sonarpur" },
    { name: "Asansol Engineering College, Asansol, Burdwan", checkbox: false, value: "Asansol Engineering College, Asansol, Burdwan" },
    { name: "Techno India University, Kolkata", checkbox: false, value: "Techno India University, Kolkata" },
    { name: "MCKV Institute Of Engineering, Liluah, Howrah", checkbox: false, value: "MCKV Institute Of Engineering, Liluah, Howrah" },
    { name: "Calcutta Institute of Engineering & Management", checkbox: false, value: "Calcutta Institute of Engineering & Management" },
    { name: "Atal Bihari Vajpayee Indian Institute Of Information Technology- Gwalior", checkbox: false, value: "Atal Bihari Vajpayee Indian Institute Of Information Technology- Gwalior" },
    { name: "Pandit Dwarka Prasad Mishra Indian Institute Of Information Technology, Design And Manufacturing, Jabalpur (IIITDM)", checkbox: false, value: "Pandit Dwarka Prasad Mishra Indian Institute Of Information Technology, Design And Manufacturing, Jabalpur (IIITDM)" },
    { name: "Indian Institute of Information Technology, Chittoor", checkbox: false, value: "Indian Institute of Information Technology, Chittoor" },
    { name: "Indian Institute of Information Technology, Vadodara", checkbox: false, value: "Indian Institute of Information Technology, Vadodara" },
    { name: "Indian Institute of Information Technology, Una, HP", checkbox: false, value: "Indian Institute of Information Technology, Una, HP" },
    { name: "SGSITS, Indore", checkbox: false, value: "SGSITS, Indore" },
    { name: "Madhav Institute Of Technology And Science", checkbox: false, value: "Madhav Institute Of Technology And Science" },
    { name: "Army Institute Of Technology", checkbox: false, value: "Army Institute Of Technology" },
    { name: "Bharath Institute of Higher Education and Research", checkbox: false, value: "Bharath Institute of Higher Education and Research" },
    { name: "B.S. A. Crescent Institute of Science & Technology", checkbox: false, value: "B.S. A. Crescent Institute of Science & Technology" },
    { name: "L.D.College of Engineering, Ahmedabad", checkbox: false, value: "L.D.College of Engineering, Ahmedabad" },
    { name: "Sardar Vallabhbhai Patel Institute of Technology (SVIT), Vasad", checkbox: false, value: "Sardar Vallabhbhai Patel Institute of Technology (SVIT), Vasad" },
    { name: "Babaria Institute of Technology, Vadodara", checkbox: false, value: "Babaria Institute of Technology, Vadodara" },
    { name: "SAL Institute of Technology & Engineering Research, Ahmedabad", checkbox: false, value: "SAL Institute of Technology & Engineering Research, Ahmedabad" },
    { name: "SAL College of Engineering, Sola Road, Ahmedabad", checkbox: false, value: "SAL College of Engineering, Sola Road, Ahmedabad" },
    { name: "SAL Education Campus, Ahmedabad", checkbox: false, value: "SAL Education Campus, Ahmedabad" },
    { name: "Amity University, Jaipur", checkbox: false, value: "Amity University, Jaipur" },
    { name: "Arya Institute of Engineering & Technology, Jaipur", checkbox: false, value: "Arya Institute of Engineering & Technology, Jaipur" },
    { name: "Jaipur Engineering College & Research Centre, Jaipur", checkbox: false, value: "Jaipur Engineering College & Research Centre, Jaipur" },
    { name: "Poornima Institute of Engineering & Technology, Jaipur", checkbox: false, value: "Poornima Institute of Engineering & Technology, Jaipur" },
    { name: "Arya College of Engineering & Information Technology, Jaipur", checkbox: false, value: "Arya College of Engineering & Information Technology, Jaipur" },
    { name: "Global Institute of Technology, Jaipur", checkbox: false, value: "Global Institute of Technology, Jaipur" },
    { name: "Poornima College of Engineering, Jaipur", checkbox: false, value: "Poornima College of Engineering, Jaipur" },
    { name: "Swami Keshwanand Institute of Technology Management & Gramothan, Jaipur", checkbox: false, value: "Swami Keshwanand Institute of Technology Management & Gramothan, Jaipur" },
    { name: "Sathyabama Institute of Science and Technology", checkbox: false, value: "Sathyabama Institute of Science and Technology" },
  ],
  kycDate: '2099-10-31'
};
