apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapwebuat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udapwebuat
  template:
    metadata:
      labels:
        app: udapwebuat
    spec:
      containers:
        - name: udapwebuat
          image: lxpacrazure.azurecr.io/udapwebuat:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret